/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Demo } from "./Demo";
import { DemoCountArgs } from "./DemoCountArgs";
import { DemoFindManyArgs } from "./DemoFindManyArgs";
import { DemoFindUniqueArgs } from "./DemoFindUniqueArgs";
import { DeleteDemoArgs } from "./DeleteDemoArgs";
import { DemoService } from "../demo.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Demo)
export class DemoResolverBase {
  constructor(
    protected readonly service: DemoService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Demo",
    action: "read",
    possession: "any",
  })
  async _demosMeta(
    @graphql.Args() args: DemoCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Demo])
  @nestAccessControl.UseRoles({
    resource: "Demo",
    action: "read",
    possession: "any",
  })
  async demos(@graphql.Args() args: DemoFindManyArgs): Promise<Demo[]> {
    return this.service.demos(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Demo, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Demo",
    action: "read",
    possession: "own",
  })
  async demo(@graphql.Args() args: DemoFindUniqueArgs): Promise<Demo | null> {
    const result = await this.service.demo(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Demo)
  @nestAccessControl.UseRoles({
    resource: "Demo",
    action: "delete",
    possession: "any",
  })
  async deleteDemo(@graphql.Args() args: DeleteDemoArgs): Promise<Demo | null> {
    try {
      return await this.service.deleteDemo(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
